import { createContext, useContext, useState } from 'react'

const translations = {
  es: {
    nav: {
      about: 'Sobre mí',
      stack: 'Stack',
      projects: 'Proyectos',
      process: 'Proceso',
      pricing: 'Precios',
      contact: 'Contacto',
    },
    hero: {
      available: 'Disponible para proyectos',
      greeting: 'Hola, soy',
      tagline: 'No construyo páginas web.',
      tagline2: 'Construyo tu presencia digital.',
      description:
        'Desarrollador Web Fullstack con 4 años creando soluciones digitales para universidades, empresas y emprendedores. Tu negocio merece estar en internet — bien hecho.',
      cta_primary: 'Ver proyectos',
      cta_secondary: 'Hablemos',
      stat1_value: '4+',
      stat1_label: 'Años de experiencia',
      stat2_value: '20+',
      stat2_label: 'Proyectos completados',
      stat3_value: '100%',
      stat3_label: 'Dedicación',
    },
    about: {
      label: 'Sobre mí',
      title: 'Código con propósito.',
      title2: 'Resultados con impacto.',
      quote: 'Somos lo que hacemos repetidamente. La excelencia entonces, no es un acto, sino un hábito.',
      quote_author: 'Aristóteles',
      p1: 'Soy economista de formación y desarrollador por vocación. Esa combinación inusual me da algo que pocos tienen: entiendo los números de tu negocio tanto como el código que lo hace crecer.',
      p2: 'Empecé en 2021 de forma autodidacta en Platzi, llegué a mi primer empleo formal como fullstack en una empresa peruana en 2023 y entre 2024 y 2025 desarrollé páginas web y software a la medida para fundaciones, empresas industriales y proyectos de análisis de datos. Hoy trabajo como analista en la Universidad del Magdalena, donde construyo sistemas de información y herramientas de seguimiento institucional.',
      p3: 'Como freelancer, pongo ese bagaje al servicio de tu proyecto. No vengo a vender páginas — vengo a resolver problemas reales con tecnología real. Ya sea que tengas todo claro o no sepas por dónde empezar, aquí estoy para convertir tu visión en algo que funcione, se vea bien y trabaje por tu negocio las 24 horas.',
      exp_title: 'Trayectoria',
      experiences: [
        {
          year: '2021 — 2023',
          role: 'Formación Autodidacta',
          org: 'Platzi & Proyectos Propios',
          desc: 'Aprendizaje de desarrollo web a través de Platzi y construcción de proyectos personales para consolidar habilidades frontend y backend.',
        },
        {
          year: '2023 — 2024',
          role: 'Desarrollador Fullstack',
          org: 'Empresa de Software · Perú',
          desc: 'Primer empleo como desarrollador fullstack en empresa peruana, construyendo soluciones web completas para clientes corporativos.',
        },
        {
          year: '2024 — 2025',
          role: 'Desarrollador Freelance',
          org: 'Clientes Independientes',
          desc: 'Páginas web y software a medida para fundaciones, empresas de maquinaria pesada, sistemas de información política y dashboards de monitoreo.',
        },
        {
          year: '2025 — Presente',
          role: 'Analista & Desarrollador Web',
          org: 'Universidad del Magdalena',
          desc: 'Desarrollo de instrumentos de seguimiento para recolecta de información, sistemas financieros y herramientas digitales institucionales.',
        },
      ],
    },
    stack: {
      label: 'Herramientas',
      title: 'El arsenal.',
      subtitle:
        'Tecnologías con las que construyo experiencias digitales robustas, escalables y hermosas.',
      tabs: ['Frontend', 'Backend', 'Bases de datos', 'Herramientas'],
      frontend: [
        { name: 'HTML5', icon: 'devicon-html5-plain colored', level: 'Experto' },
        { name: 'CSS3', icon: 'devicon-css3-plain colored', level: 'Experto' },
        { name: 'JavaScript', icon: 'devicon-javascript-plain colored', level: 'Experto' },
        { name: 'TypeScript', icon: 'devicon-typescript-plain colored', level: 'Avanzado' },
        { name: 'React', icon: 'devicon-react-original colored', level: 'Experto' },
        { name: 'Tailwind CSS', icon: 'devicon-tailwindcss-plain colored', level: 'Experto' },
      ],
      backend: [
        { name: 'Node.js', icon: 'devicon-nodejs-plain colored', level: 'Avanzado' },
        { name: 'Python', icon: 'devicon-python-plain colored', level: 'Avanzado' },
        { name: 'FastAPI', icon: 'devicon-fastapi-plain colored', level: 'Avanzado' },
        { name: 'Express', icon: 'devicon-express-original', level: 'Avanzado' },
      ],
      database: [
        { name: 'PostgreSQL', icon: 'devicon-postgresql-plain colored', level: 'Avanzado' },
        { name: 'MySQL', icon: 'devicon-mysql-plain colored', level: 'Avanzado' },
        { name: 'TypeORM', icon: 'devicon-typescript-plain colored', level: 'Avanzado' },
        { name: 'Sequelize', icon: 'devicon-sequelize-plain colored', level: 'Intermedio' },
      ],
      tools: [
        { name: 'Git', icon: 'devicon-git-plain colored', level: 'Experto' },
        { name: 'GitHub', icon: 'devicon-github-original', level: 'Experto' },
        { name: 'VS Code', icon: 'devicon-vscode-plain colored', level: 'Experto' },
        { name: 'Vite', icon: 'devicon-vitejs-plain colored', level: 'Avanzado' },
        { name: 'Figma', icon: 'devicon-figma-plain colored', level: 'Intermedio' },
      ],
    },
    projects: {
      label: 'Proyectos',
      title: 'Trabajo real.',
      subtitle:
        'Seis páginas completas diseñadas y desarrolladas de cero — cada una con identidad propia, código limpio y animaciones profesionales.',
      cta: 'Quiero ser el primero',
      badge: 'Próximamente',
      special_text: 'Tu sector también puede ser parte de esto — ',
      special_link: 'hablemos',
    },
    process: {
      label: 'Proceso',
      title: '¿Cómo trabajo?',
      subtitle: 'Sin sorpresas. Sin retrasos. Con resultados.',
      steps: [
        {
          num: '01',
          title: 'Escucho',
          desc: 'Primero entiendo tu negocio, tu público y tus objetivos reales. Sin este paso, nada que construya tendrá sentido.',
        },
        {
          num: '02',
          title: 'Estrategia',
          desc: 'Defino la estructura, el contenido y la arquitectura ideal para tu caso específico. No hay soluciones genéricas.',
        },
        {
          num: '03',
          title: 'Diseño & Desarrollo',
          desc: 'Primero diseñamos juntos: paleta de colores, tipografía, estructura y estilo visual hasta que lo apruebes. Luego construyo todo con código limpio, rápido y optimizado para buscadores.',
        },
        {
          num: '04',
          title: 'Entrega',
          desc: 'Deploy, pruebas completas, capacitación y soporte inicial. Para páginas web el tiempo de entrega es de 7 a 15 días; el software a la medida tiene un plazo variable según el alcance del proyecto.',
        },
      ],
    },
    contact: {
      label: 'Contacto',
      title: '¿Tienes un proyecto?',
      title2: 'Hablemos.',
      subtitle:
        'Cuéntame de tu negocio o idea. La primera consulta es completamente gratis y sin ningún compromiso.',
      email_label: 'Email directo',
      linkedin_label: 'LinkedIn',
      github_label: 'GitHub',
      availability: 'Actualmente disponible',
      availability_desc: 'Acepto proyectos nuevos y respondo en menos de 24 horas.',
    },
    footer: {
      tagline: 'Transformando ideas en presencias digitales que funcionan.',
      rights: 'Todos los derechos reservados.',
      made: 'Diseñado y construido por',
    },
    pricing: {
      label: 'Inversión',
      title: 'Precios claros,',
      title2: 'sin sorpresas.',
      subtitle: 'Sabes exactamente lo que recibes y cuánto pagas desde el primer día.',
      plans: [
        {
          id: 'landing',
          badge: 'Más popular',
          name: 'Landing Page',
          desc: 'Todo lo que necesita tu negocio para tener presencia digital profesional que trabaje por ti las 24 horas.',
          price: '$550.000',
          currency: 'COP',
          period: 'pago único',
          featured: true,
          included: [
            'Diseño visual personalizado',
            'Desarrollo completo',
            'Optimizado para móviles',
            'SEO técnico básico',
            'Despliegue incluido',
            'Entrega en 7 a 15 días',
          ],
          note: 'Dominio y hosting no incluidos (opcionales, muy económicos). Si lo prefieres, el deploy puede hacerse gratis con dominio público.',
          cta: 'Quiero mi Landing Page',
        },
        {
          id: 'custom',
          badge: 'A tu medida',
          name: 'Plataforma a Medida',
          desc: 'Software web completo con backend, bases de datos, autenticación y todo lo que tu proyecto necesite.',
          price: 'Cotización',
          currency: '',
          period: 'según alcance',
          featured: false,
          included: [
            'Backend y API REST',
            'Base de datos (PostgreSQL / MySQL)',
            'Autenticación de usuarios',
            'Panel de administración',
            'Funciones completamente a tu medida',
            'Soporte extendido post-entrega',
          ],
          note: '',
          cta: 'Solicitar cotización',
        },
      ],
      payment_label: 'Proceso de pago',
      payment_title: 'Simple y justo para ambas partes',
      payment_subtitle: 'Sin pagar todo por adelantado. Tu inversión protegida en cada etapa.',
      payment_steps: [
        { icon: '50%', title: 'Al inicio', desc: 'Confirmamos el proyecto y arrancamos.', highlight: true },
        { icon: '⚙️', title: 'Desarrollo', desc: 'Construyo tu proyecto según lo acordado.', highlight: false },
        { icon: '✅', title: 'Tu aprobación', desc: 'Revisas y apruebas el resultado final.', highlight: false },
        { icon: '50%', title: 'Antes del deploy', desc: 'Segundo pago antes de publicar.', highlight: true },
        { icon: '🚀', title: 'Lanzamiento', desc: '¡Tu sitio ya está en internet!', highlight: false },
      ],
      affiliate_badge: 'Programa de Afiliados',
      affiliate_title: '¿Conoces a alguien que necesite una web?',
      affiliate_subtitle: 'Refiere clientes y gana una comisión real por cada proyecto que se concrete.',
      affiliate_tiers: [
        {
          type: 'Landing Pages',
          icon: '🌐',
          commission: '$50.000',
          currency: 'COP',
          note: 'por cada landing entregada al cliente',
          color: '#60a5fa',
        },
        {
          type: 'Proyectos a Medida',
          icon: '⚡',
          commission: '5% – 10%',
          currency: '',
          note: 'del valor total del proyecto',
          color: '#a78bfa',
        },
      ],
      affiliate_note: 'El pago de la comisión se realiza inmediatamente después de la entrega final al cliente.',
      affiliate_cta: 'Quiero ser afiliado',
    },
  },

  en: {
    nav: {
      about: 'About',
      stack: 'Stack',
      projects: 'Projects',
      process: 'Process',
      pricing: 'Pricing',
      contact: 'Contact',
    },
    hero: {
      available: 'Available for projects',
      greeting: "Hi, I'm",
      tagline: "I don't build websites.",
      tagline2: 'I build your digital presence.',
      description:
        'Fullstack Web Developer with 4+ years building digital solutions for universities, businesses, and entrepreneurs. Your business deserves to be online — done right.',
      cta_primary: 'See projects',
      cta_secondary: "Let's talk",
      stat1_value: '4+',
      stat1_label: 'Years of experience',
      stat2_value: '20+',
      stat2_label: 'Projects completed',
      stat3_value: '100%',
      stat3_label: 'Dedication',
    },
    about: {
      label: 'About me',
      title: 'Code with purpose.',
      title2: 'Results with impact.',
      quote: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.',
      quote_author: 'Aristotle',
      p1: "I'm an economist by training and a developer by vocation. That unusual combination gives me something few have: I understand your business numbers as well as the code that makes it grow.",
      p2: "I started teaching myself through Platzi in 2021, landed my first fullstack job at a Peruvian company in 2023, and between 2024 and 2025 built web pages and custom software for foundations, industrial companies, and data analysis projects. Today I work as an analyst at the University of Magdalena, building information systems and institutional tracking tools.",
      p3: "As a freelancer, I bring all that experience to your project. I'm not here to sell pages — I'm here to solve real problems with real technology. Whether you have everything figured out or don't know where to start, I'm here to turn your vision into something that works, looks great, and drives results 24/7.",
      exp_title: 'Experience',
      experiences: [
        {
          year: '2021 — 2023',
          role: 'Self-Taught Training',
          org: 'Platzi & Personal Projects',
          desc: 'Self-taught web development through Platzi and personal projects to build solid frontend and backend skills.',
        },
        {
          year: '2023 — 2024',
          role: 'Fullstack Developer',
          org: 'Software Company · Peru',
          desc: 'First job as a fullstack developer at a Peruvian company, building complete web solutions for corporate clients.',
        },
        {
          year: '2024 — 2025',
          role: 'Freelance Developer',
          org: 'Independent Clients',
          desc: 'Web pages and custom software for foundations, heavy machinery companies, political information systems, and monitoring dashboards.',
        },
        {
          year: '2025 — Present',
          role: 'Analyst & Web Developer',
          org: 'University of Magdalena',
          desc: 'Development of tracking instruments for data collection, financial systems, and institutional digital tools.',
        },
      ],
    },
    stack: {
      label: 'Tools',
      title: 'The arsenal.',
      subtitle: 'Technologies I use to build robust, scalable, and beautiful digital experiences.',
      tabs: ['Frontend', 'Backend', 'Databases', 'Tools'],
      frontend: [
        { name: 'HTML5', icon: 'devicon-html5-plain colored', level: 'Expert' },
        { name: 'CSS3', icon: 'devicon-css3-plain colored', level: 'Expert' },
        { name: 'JavaScript', icon: 'devicon-javascript-plain colored', level: 'Expert' },
        { name: 'TypeScript', icon: 'devicon-typescript-plain colored', level: 'Advanced' },
        { name: 'React', icon: 'devicon-react-original colored', level: 'Expert' },
        { name: 'Tailwind CSS', icon: 'devicon-tailwindcss-plain colored', level: 'Expert' },
      ],
      backend: [
        { name: 'Node.js', icon: 'devicon-nodejs-plain colored', level: 'Advanced' },
        { name: 'Python', icon: 'devicon-python-plain colored', level: 'Advanced' },
        { name: 'FastAPI', icon: 'devicon-fastapi-plain colored', level: 'Advanced' },
        { name: 'Express', icon: 'devicon-express-original', level: 'Advanced' },
      ],
      database: [
        { name: 'PostgreSQL', icon: 'devicon-postgresql-plain colored', level: 'Advanced' },
        { name: 'MySQL', icon: 'devicon-mysql-plain colored', level: 'Advanced' },
        { name: 'TypeORM', icon: 'devicon-typescript-plain colored', level: 'Advanced' },
        { name: 'Sequelize', icon: 'devicon-sequelize-plain colored', level: 'Intermediate' },
      ],
      tools: [
        { name: 'Git', icon: 'devicon-git-plain colored', level: 'Expert' },
        { name: 'GitHub', icon: 'devicon-github-original', level: 'Expert' },
        { name: 'VS Code', icon: 'devicon-vscode-plain colored', level: 'Expert' },
        { name: 'Vite', icon: 'devicon-vitejs-plain colored', level: 'Advanced' },
        { name: 'Figma', icon: 'devicon-figma-plain colored', level: 'Intermediate' },
      ],
    },
    projects: {
      label: 'Projects',
      title: 'Real work.',
      subtitle:
        'Six complete pages designed and developed from scratch — each with its own identity, clean code and professional animations.',
      cta: 'Be the first',
      badge: 'Coming soon',
      special_text: 'Your sector can be part of this too — ',
      special_link: "let's talk",
    },
    process: {
      label: 'Process',
      title: 'How I work.',
      subtitle: 'No surprises. No delays. Real results.',
      steps: [
        {
          num: '01',
          title: 'Listen',
          desc: 'First I understand your business, your audience, and your real goals. Without this step, nothing I build will make sense.',
        },
        {
          num: '02',
          title: 'Strategy',
          desc: 'I define the structure, content, and ideal architecture for your specific case. No generic solutions.',
        },
        {
          num: '03',
          title: 'Design & Development',
          desc: "First we design together: color palette, typography, structure and visual style until you approve it. Then I build everything with clean, fast, search-engine-optimized code.",
        },
        {
          num: '04',
          title: 'Delivery',
          desc: "Deploy, complete testing, training, and initial support. Web pages are delivered in 7 to 15 days; custom software timelines vary depending on the project scope.",
        },
      ],
    },
    contact: {
      label: 'Contact',
      title: 'Have a project?',
      title2: "Let's talk.",
      subtitle:
        'Tell me about your business or idea. The first consultation is completely free and no-commitment.',
      email_label: 'Direct email',
      linkedin_label: 'LinkedIn',
      github_label: 'GitHub',
      availability: 'Currently available',
      availability_desc: 'Accepting new projects — replies within 24 hours.',
    },
    footer: {
      tagline: 'Turning ideas into digital presences that work.',
      rights: 'All rights reserved.',
      made: 'Designed and built by',
    },
    pricing: {
      label: 'Investment',
      title: 'Clear prices,',
      title2: 'no surprises.',
      subtitle: 'You know exactly what you get and how much you pay, from day one.',
      plans: [
        {
          id: 'landing',
          badge: 'Most popular',
          name: 'Landing Page',
          desc: "Everything your business needs for a professional digital presence that works for you around the clock.",
          price: '$550.000',
          currency: 'COP',
          period: 'one-time payment',
          featured: true,
          included: [
            'Custom visual design',
            'Complete development',
            'Mobile-optimized',
            'Basic technical SEO',
            'Deployment included',
            'Delivered in 7 to 15 days',
          ],
          note: 'Domain & hosting not included (optional, very affordable). Free deployment with a public domain is also available.',
          cta: 'Get my Landing Page',
        },
        {
          id: 'custom',
          badge: 'Tailored',
          name: 'Custom Platform',
          desc: 'Complete web software with backend, databases, authentication, and everything your project needs.',
          price: 'Quote',
          currency: '',
          period: 'based on scope',
          featured: false,
          included: [
            'Backend & REST API',
            'Database (PostgreSQL / MySQL)',
            'User authentication',
            'Admin dashboard',
            'Fully custom features',
            'Extended post-launch support',
          ],
          note: '',
          cta: 'Request a quote',
        },
      ],
      payment_label: 'Payment process',
      payment_title: 'Simple and fair for both sides',
      payment_subtitle: 'No full upfront payment. Your investment protected at every stage.',
      payment_steps: [
        { icon: '50%', title: 'At start', desc: 'We confirm the project and get to work.', highlight: true },
        { icon: '⚙️', title: 'Development', desc: 'I build your project as agreed.', highlight: false },
        { icon: '✅', title: 'Your approval', desc: 'You review and approve the final result.', highlight: false },
        { icon: '50%', title: 'Before deploy', desc: 'Final payment before publishing online.', highlight: true },
        { icon: '🚀', title: 'Launch', desc: 'Your site is live on the internet!', highlight: false },
      ],
      affiliate_badge: 'Affiliate Program',
      affiliate_title: 'Know someone who needs a website?',
      affiliate_subtitle: 'Refer clients and earn a real commission for every project that happens.',
      affiliate_tiers: [
        {
          type: 'Landing Pages',
          icon: '🌐',
          commission: '$50.000',
          currency: 'COP',
          note: 'per landing page delivered to the client',
          color: '#60a5fa',
        },
        {
          type: 'Custom Projects',
          icon: '⚡',
          commission: '5% – 10%',
          currency: '',
          note: 'of the total project value',
          color: '#a78bfa',
        },
      ],
      affiliate_note: 'Commission is paid immediately after final delivery to the client.',
      affiliate_cta: 'Become an affiliate',
    },
  },
}

const LanguageContext = createContext(null)

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('es')
  const toggle = () => setLang((l) => (l === 'es' ? 'en' : 'es'))
  return (
    <LanguageContext.Provider value={{ lang, toggle, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)
